services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: murmu
      POSTGRES_PASSWORD: murmu
      POSTGRES_DB: murmu
    ports:
      - "5432:5432"
    volumes:
      - murmu-postgres:/var/lib/postgresql/data

volumes:
  murmu-postgres:

